apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  labels:
    app.kubernetes.io/name: radarr
spec:
  secretName: radarr-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
  - radarr.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
