---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`radarr.xmple.io`)
    kind: Rule
    services:
    - name: radarr
      port: 80
  tls:
    secretName: radarr-tls
    options:
      name: mintls13
      namespace: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  secretName: radarr-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
  - radarr.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
