apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/linuxserver/radarr
    newTag: 5.25.0
resources:
  - ../../base
