apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  labels:
    app.kubernetes.io/name: plex
spec:
  ingressClassName: cilium
  rules:
    - host: plex.xmple.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  name: pms
  tls:
    - secretName: plex-tls
      hosts:
        - plex.xmple.io
