apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: longhorn-storage
      app.kubernetes.io/part-of: db3000
resources:
- recurringjobs.yaml
- storageclass.yaml
