---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: db3000-snapshot
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 * * * *
  groups:
    - db3000
  retain: 24
  task: snapshot
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: db3000-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups:
    - db3000
  retain: 7
  task: backup
