apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/fallenbagel/jellyseerr
    newTag: 2.3.0
resources:
  - ../../base
