apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ombi-tls
  labels:
    app.kubernetes.io/name: ombi
spec:
  secretName: ombi-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
  - db3000.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
