apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ombi
  labels:
    app.kubernetes.io/name: ombi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`db3000.xmple.io`) && PathPrefix(`/ombi/`)
      kind: Rule
      services:
        - name: ombi
          port: 80
  tls:
    secretName: db3000-tls
    options:
      name: mintls13
      namespace: traefik
