kind: Secret
apiVersion: v1
metadata:
  name: media-smb-creds
  annotations:
    avp.kubernetes.io/path: secret/data/db3000/media-share/credentials
type: Opaque
data:
  username: <username | base64encode>
  password: <password | base64encode>
