apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: media-smb-creds
spec:
  provider: vault
  secretObjects:
  - secretName: media-smb-creds
    type: Opaque
    data:
    - key: username
      objectName: username
    - key: password
      objectName: password
  parameters:
    roleName: db3000
    vaultAddress: https://vault.xmple.io:8200
    vaultSkipTLSVerify: 'true'
    objects: |
      - secretPath: "secret/data/db3000/media-share/credentials"
        objectName: username
        secretKey: username
      - secretPath: "secret/data/db3000/media-share/credentials"
        objectName: password
        secretKey: password
