apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: media-smb-creds
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: media-smb-creds
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/db3000/media-share/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: secret/db3000/media-share/credentials
        property: password
