apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- credentials.yaml
- pv.yaml
configurations:
- kustomizeconfig.yaml

# This is hard-coded until I can figure out why ArgoCD 
# doesn't updated the nodeStageSecretRef namespace.
namespace: db3000