---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-media-share
spec:
  storageClassName: smb-media-share
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - dir_mode=0770
  - file_mode=0660
  - uid=911
  - gid=911
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: db3000-media-share
    volumeAttributes:
      source: "//10.1.1.30/Plex Media"
    nodeStageSecretRef:
      name: media-smb-creds
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-media-share-sync
spec:
  storageClassName: smb-media-share-sync
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - dir_mode=0770
  - file_mode=0660
  - uid=911
  - gid=911
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: db3000-media-share-sync
    volumeAttributes:
      source: "//10.1.1.30/Sync Media"
    nodeStageSecretRef:
      name: media-smb-creds
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-share
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: db3000-media-share
  storageClassName: smb-media-share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-share-sync
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: db3000-media-share-sync
  storageClassName: smb-media-share-sync
