apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/linuxserver/tautulli
    newTag: 2.14.5
resources:
  - ../../base
