apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nzbget
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: db3000
#  syncPolicy:
#    automated: {}
  destination:
    namespace: db3000
    server: {{ .Values.spec.destination.server }}
  source:
    path: nzbget/overlays/prod
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin: 
      name: argocd-vault-plugin-kustomize
