apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: db3000
  destination:
    namespace: db3000
    server: {{ .Values.spec.destination.server }}
  source:
    path: overseerr/overlays/prod
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true
