---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: db3000
  syncPolicy:
    automated: {}
  destination:
    namespace: sonarr
    server: {{ .Values.spec.destination.server }}
  source:
    path: sonarr/overlays/prod
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
