apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: sonarr
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: db3000
  syncPolicy:
    automated: {}
  destination:
    namespace: sonarr
    server: {{ .Values.spec.destination.server }}
  source:
    path: sonarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
