---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-ui
  labels:
    app.kubernetes.io/name: syncthing
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: web-ui
  selector:
    app.kubernetes.io/name: syncthing
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-lb
  labels:
    app.kubernetes.io/name: syncthing
  annotations:
    lbipam.cilium.io/ips: "10.1.1.53"
    lbipam.cilium.io/sharing-key: db3000-lb
spec:
  ports:
    - name: syncthing-tcp
      port: 22000
      targetPort: syncthing-tcp
      nodePort: 30174
      protocol: TCP
    - name: syncthing-udp
      port: 22000
      targetPort: syncthing-udp
      nodePort: 30174
      protocol: UDP
  selector:
    app.kubernetes.io/name: syncthing
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
