apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr
          imagePullPolicy: Always
          ports:
            - containerPort: 9696
              name: http
              protocol: TCP
#          livenessProbe:
#             httpGet:
#               path: /notifications
#               port: http
#             initialDelaySeconds: 60
#           readinessProbe:
#             httpGet:
#               path: /notifications
#               port: http
          envFrom:
            - configMapRef:
                name: prowlarr-config
          resources:
            limits:
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 384Mi
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
