apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: db3000-ingress
    credentials-file: /config/credentials.json
    no-autoupdate: true
    ingress:
    - hostname: sonarr.xmple.io
      service: http://sonarr:80
    - service: http_status:404
