apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: db3000-ingress
    credentials-file: /etc/cloudflared/config/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: sonarr.xmple.io
      service: http://sonarr:80
    - hostname: test.xmple.io
      service: hello_world
    - service: http_status:404
