apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        imagePullPolicy: IfNotPresent
        command: ["cloudflared"]
        args: ["tunnel", "--config", "/config/config.yaml"]
        resources:
          requests:
            memory: 200Mi
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: cloudflared-config
          - secret:
              name: cloudflared-credentials
