apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        imagePullPolicy: IfNotPresent
        args: ["tunnel", "--config", "/etc/cloudflared/config/config.yaml"]
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/cloudflared/config
          name: config
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: cloudflared-config
          - secret:
              name: cloudflared-credentials
