apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      PodAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - cloudflared
          topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        imagePullPolicy: IfNotPresent
        command: ['cloudflared', 'tunnel']
        args:
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /etc/cloudflared/config
          name: config
          readOnly: true
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: cloudflared-config
          - secret:
              name: cloudflared-credentials
