apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudflared-credentials
    template:
      type: Opaque
      data:
        credentials.json: "{{ .credentials | toString }}"
  data:
    - secretKey: credentials
      remoteRef:
        key: secret/k3s/cloudflare/argo-tunnel/db3000/credentials
