apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: db3000
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: nzbget
      app.kubernetes.io/name: nzbget
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nzbget
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: nzbget
        image: linuxserver/nzbget:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6789
          name: http
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
        readinessProbe:
          tcpSocket:
            port: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "911"
        - name: PGID
          value: "911"
        - name: UMASK_SET
          value: "0077"
        resources:
          requests:
            memory: 100Mi
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: media
          subPath: Scratch/Download/NZBGet
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nzbget-config
      - name: media
        persistentVolumeClaim:
          claimName: media-share
