apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget
  namespace: db3000
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  ingressClassName: traefik
  rules:
  - host: nzbget.xmple.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzbget
            port:
              name: http
  tls:
  - hosts:
    - nzbget.xmple.io
    secretName: nzbget-tls
