apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/linuxserver/transmission
    newTag: version-4.0.5
  - name: docker.io/qmcgaw/gluetun
    newTag: v3.38.0
resources:
  - ../../base
