apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-tls
  labels:
    app.kubernetes.io/name: overseerr
spec:
  secretName: overseerr-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - overseerr.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
