apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/linuxserver/bazarr
    newTag: 1.4.4
resources:
  - ../../base
