apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db3000
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: resilio/sync
    newTag: 2.7.3
resources:
  - ../../base
