---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-jellyfin-config
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-db3000
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: db3000-jellyfin-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-jellyfin-cache
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-db3000
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: db3000-jellyfin-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: db3000-jellyfin-config
  storageClassName: longhorn-db3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: db3000-jellyfin-cache
  storageClassName: longhorn-db3000
