apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`db3000.xmple.io`) && PathPrefix(`/bazarr/`)
      kind: Rule
      services:
        - name: bazarr
          port: 80
      middlewares:
        - name: forwardauth-authelia
          namespace: authelia
  tls:
    secretName: bazarr-tls
    options:
      name: mintls13
      namespace: traefik
