apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
namespace:
- kind: PersistentVolume
  path: spec/claimRef/namespace