apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: db3000-tls
  labels:
    app.kubernetes.io/name: db3000
spec:
  secretName: db3000-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - db3000.xmple.io
    - plex.xmple.io
    - overseerr.xmple.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
