apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: db3000
resources:
  - certificate.yaml
  - gateway.yaml
  - routes.yaml
  - middleware.yaml
  - tlsoption.yaml