---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: db3000
spec:
  blocks:
    - start: "10.1.1.53"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: db3000
