apiVersion: v1
kind: Secret
metadata:
  name: resilio-veeam-creds
  labels:
    app.kubernetes.io/name: resilio
  annotations:
    avp.kubernetes.io/path: secret/data/db3000/resilio/smb-credentials
type: Opaque
data:
  username: <username | base64encode>
  password: <password | base64encode>
