apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: resilio
  app.kubernetes.io/part-of: db3000
resources:
- config.yaml
- credentials.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- certificate.yaml
configurations:
- kustomizeconfig.yaml
