---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-resilio-sync-db
  labels:
    app.kubernetes.io/name: resilio
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-db3000
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: db3000-resilio-sync-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-sync-db
  labels:
    app.kubernetes.io/name: resilio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: db3000-resilio-sync-db
  storageClassName: longhorn-db3000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-resilio-veeam
  labels:
    app.kubernetes.io/name: resilio
spec:
  storageClassName: smb-resilio-sync-veeam
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - dir_mode=0770
  - file_mode=0660
  - uid=1100
  - gid=1100
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: db3000-resilio-veeam
    volumeAttributes:
      source: "//10.1.1.30/Veeam Backups"
    nodeStageSecretRef:
      name: resilio-veeam-creds
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-veeam
  labels:
    app.kubernetes.io/name: resilio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: db3000-resilio-veeam
  storageClassName: smb-resilio-sync-veeam
