---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyseerr-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jellyseerr-secrets
    template:
      type: Opaque
      data:
        DB_TYPE: "{{ .type }}"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DB_NAME: "{{ .database }}"
        DB_USER: "{{ .username }}"
        DB_PASS: "{{ .password }}"
  data:
    - secretKey: type
      remoteRef:
        key: secret/db3000/jellyseerr/database
        property: type
    - secretKey: host
      remoteRef:
        key: secret/db3000/jellyseerr/database
        property: host
    - secretKey: port
      remoteRef:
        key: secret/db3000/jellyseerr/database
        property: port
    - secretKey: database
      remoteRef:
        key: secret/db3000/jellyseerr/database
        property: database
    - secretKey: username
      remoteRef:
        key: secret/db3000/jellyseerr/database
        property: username
    - secretKey: password
      remoteRef:
        key: secret/db3000/jellyseerr/database
        property: password