apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-tls
  labels:
    app.kubernetes.io/name: sonarr
spec:
  secretName: sonarr-tls
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
  - sonarr.xmple.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
