apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: sonarr
  app.kubernetes.io/part-of: db3000
resources:
- config.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- certificate.yaml
- ingress.yaml
