---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-sonarr-config
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    name: sonarr-config
    namespace: sonarr
  storageClassName: longhorn-db3000
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: db3000-sonarr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: db3000-sonarr-config
  storageClassName: longhorn-db3000
