---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  labels:
    app.kubernetes.io/name: transmission
data:
  TZ: Europe/London
  PGID: "1001"
  PUID: "568"
  UMASK: "007"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-vpn-config
  labels:
    app.kubernetes.io/name: transmission
data:
  TZ: Europe/London
  DOT: "on"
  FIREWALL_DEBUG: "on"
  FIREWALL_INPUT_PORTS: "8888,9091,51413"
  HTTPPROXY: "on"
  HTTPPROXY_LOG: "on"
  #DNS_KEEP_NAMESERVER: "on"