apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  labels:
    app.kubernetes.io/name: transmission
data:
  TZ: Europe/London
  PGID: "1001"
  PUID: "1001"
  UMASK: "007"
  TRANSMISSION_WEB_HOME: /transmission-web-control/
