apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`transmission.xmple.io`)
      kind: Rule
      services:
        - name: transmission
          port: 80
      middlewares:
        - name: forwardauth-authelia
          namespace: authelia
  tls:
    secretName: transmission-tls
    options:
      name: mintls13
      namespace: traefik