apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: transmission
      app.kubernetes.io/part-of: db3000
resources:
  - config.yaml
  - secrets.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
