---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transmission-vpn-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: transmission-vpn-secrets
  dataFrom:
    - extract:
        key: secret/db3000/transmission/vpn
---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-proxy-credentials
type: Opaque
data:
  HTTPPROXY_USER: cHJveHl1c2Vy
  HTTPPROXY_PASSWORD: cHJveHlwYXNz
