apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vpn-secrets
  dataFrom:
    - extract:
        key: secret/db3000/transmission/vpn