---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: transmission
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-bittorrent
  labels:
    app.kubernetes.io/name: transmission
spec:
  ports:
  - name: bittorrent-tcp
    port: 51413
    protocol: TCP
  - name: bittorrent-udp
    port: 51413
    protocol: UDP
  selector:
    app.kubernetes.io/name: transmission
  type: LoadBalancer
