---
apiVersion: v1
kind: Service
metadata:
  name: transmission-bt-tcp
  namespace: db3000
  annotations:
    metallb.universe.tf/allow-shared-ip: db3000
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  ports:
  - name: bt-tcp
    port: 51413
    protocol: TCP
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
    app.kubernetes.io/component: server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-bt-udp
  namespace: db3000
  annotations:
    metallb.universe.tf/allow-shared-ip: db3000
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  ports:
  - name: bt-udp
    port: 51413
    protocol: UDP
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
    app.kubernetes.io/component: server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: db3000
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
    app.kubernetes.io/component: server
  type: ClusterIP
