apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: docker.io/jellyfin/jellyfin
    newTag: 10.10.7
resources:
  - ../../base
