apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db3000
commonLabels:
  variant: prod
images:
  - name: ghcr.io/linuxserver/syncthing
    newTag: 1.22.0
bases:
  - ../../base
