apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db3000
labels:
  - includeSelectors: true
    pairs:
      variant: prod

images:
  - name: ghcr.io/linuxserver/syncthing
    newTag: 1.23.5
resources:
  - ../../base
patches:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          cfargotunnel.com/cluster-tunnel: k3s-xmple-io
          cfargotunnel.com/fqdn: db3000.xmple.io
    target:
      version: v1
      kind: Service
      name: syncthing
