apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db3000
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/linuxserver/syncthing
    newTag: 1.29.3
resources:
  - ../../base
