apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app.kubernetes.io/name: jackett
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      containers:
      - name: jackett
        image: ghcr.io/linuxserver/jackett
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9117
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: jackett-config
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 20m
            memory: 200Mi
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: media
          subPath: Scratch/Download
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett-config
      - name: media
        persistentVolumeClaim:
          claimName: media-share
