---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-jackett-config
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-db3000
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: db3000-jackett-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: db3000
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: db3000-jackett-config
  storageClassName: longhorn-db3000
